server.port=8080
spring.application.name=resumebinder-backend

# Gemini API setting placeholder
gemini.api.key=AIzaSyD2r5ge1avZRAoByWr7c8lr1Hfngt8-euc
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
